"""Add additional fields to User model

Revision ID: 424bfa40a84b
Revises: 42f089d0ed91
Create Date: 2024-11-01 16:15:11.011866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424bfa40a84b'
down_revision = '42f089d0ed91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('display_phone', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('display_email', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pending_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pending_email')
        batch_op.drop_column('display_email')
        batch_op.drop_column('display_phone')
        batch_op.drop_column('phone')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('sex')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('address')
        batch_op.drop_column('city')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
