"""Ajout des champs cover_image et profile_image aux utilisateurs, et autres modifications

Revision ID: 5f7e0aa28047
Revises: d5971bf6c505
Create Date: 2024-11-12 00:22:51.295539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7e0aa28047'
down_revision = 'd5971bf6c505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_zoom', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profile_image_pos_x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profile_image_pos_y', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cover_image_zoom', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cover_image_pos_x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cover_image_pos_y', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cover_image_pos_y')
        batch_op.drop_column('cover_image_pos_x')
        batch_op.drop_column('cover_image_zoom')
        batch_op.drop_column('profile_image_pos_y')
        batch_op.drop_column('profile_image_pos_x')
        batch_op.drop_column('profile_image_zoom')

    # ### end Alembic commands ###
