"""Ajout des champs sport et level au modèle User

Revision ID: d5971bf6c505
Revises: 54acdddaea40
Create Date: 2024-11-11 21:45:58.141071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5971bf6c505'
down_revision = '54acdddaea40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('sport')

    # ### end Alembic commands ###
