"""Add temp field

Revision ID: f72c6a23493a
Revises:
Create Date: 2024-07-05 02:47:37.122476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72c6a23493a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'temp_field',
            sa.String(
                length=64),
            nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'temp_field')
    # ### end Alembic commands ###
